# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='2018/08/22/08/58/23/'),
        ),
    ]
