# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_auto_20180822_0858'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('n_places', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'In attesa'), (1, 'Confermata')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user_management.Restaurant')),
            ],
        ),
    ]
